version: "3.8"

services:
  monitor-node:
      image: gossip
      container_name: monitor-node
      stdin_open: true # docker run -i
      tty: true 
      command: 
        - /bin/bash
      networks: 
        - gossip-network
  
  provider-node:
    image: gossip 
    container_name: provider-node
    stdin_open: true # docker run -i
    tty: true 
    command: 
    - /bin/bash
    networks: 
      - gossip-network

  node1:
    image: gossip
    container_name: node1
    stdin_open: true # docker run -i
    tty: true 
    command: 
    - /bin/bash
    networks: 
      - gossip-network

  node2:
    image: gossip
    container_name: node2
    stdin_open: true # docker run -i
    tty: true 
    command: 
    - /bin/bash
    networks: 
      - gossip-network

  node:
    image: gossip
    stdin_open: true # docker run -i
    tty: true 
    command: 
    - /bin/bash
    networks: 
      - gossip-network

networks: 
  gossip-network:
    name: gossip-network
