version: "3"

services:
  node1:
    container_name: node1
    build:
      context: .
    ports:
      - 5001:5000
    networks: 
      - gossipNetwork

  node2:
    build:
      context: .
    container_name: node2
    ports:
      - 5002:5000
    networks: 
      - gossipNetwork

networks: 
  gossipNetwork:
    name: gossip-network
    driver: bridge